### ISSUE TITLE
ssh connection refused

### ISSUE THREAD

**Issue by MademoiselleVictoire** [blanckth/qemuTermux#1]
This is great tutorial; works like a charm. But can you please make tutorial how to ssh into running qemu vm and how to create qemu vm with aarch64 & arm .iso images?

**Comment by blanckth** [comment]
All the power and features of qemu is here on the terminal ( Termux ) you can read full documentation of [QEMU](https://www.qemu.org/docs/master/) for that and i will add some extra info if you mind but you might focus on -net option for your problem to set a bridge network and also you might check out both your inner VM os firewall and also host firewall. if this was helpful remind me to close this issue. Have fun!

**Comment by blanckth** [comment]
> This is great tutorial; works like a charm. But can you please make tutorial how to ssh into running qemu vm and how to create qemu vm with aarch64 & arm .iso images?

All the power and features of qemu is here on the terminal ( Termux ) you can read full documentation of [QEMU](https://www.qemu.org/docs/master/) for that and i will add some extra info if you mind but you might focus on -net option for your problem to set a bridge network and also you might check out both your inner VM os firewall and also host firewall. if this was helpful remind me to close this issue. Have fun!
